# Generated by Django 5.1.1 on 2024-09-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_curso_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='celular',
            field=models.CharField(max_length=11),
        ),
    ]
